// ⚠️ CRITICAL CONFIGURATION: PASTE YOUR DEPLOYED GOOGLE APPS SCRIPT WEB APP URL HERE
const API_URL = "https://script.google.com/macros/s/AKfycbz8l6bKoFpmO3WZ7-y9czEq6UM7LUitq2FF7NT9QgF2LNaVBiYhC0HuZiyNcenuwp3i/exec";
